name: Update README Profile

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（北京时间 08:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/update-readme.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Update README with latest stats
      run: |
        # 获取当前时间戳，强制刷新GitHub统计API缓存
        TIMESTAMP=$(date +%s)
        
        echo "🔄 Updating README with timestamp: $TIMESTAMP"
        
        # 显示当前README中的github-readme-stats链接
        echo "📋 Current github-readme-stats URLs:"
        grep "github-readme-stats" README.md || echo "No github-readme-stats URLs found"
        
        # 检查README.md是否存在现有的时间戳参数并替换，或者添加新的
        if grep -q "&t=" README.md; then
          # 如果已存在时间戳参数，则替换它
          sed -i "s/&t=[0-9]*//g" README.md
        fi
        
        # 为GitHub统计链接添加时间戳参数 - 使用更通用的匹配模式
        # 匹配任何用户名的github-readme-stats链接
        sed -i "s|github-readme-stats\.vercel\.app/api?username=\([^&\"]*\)\([^\"]*\)\"|github-readme-stats.vercel.app/api?username=\1\2\&t=${TIMESTAMP}\"|g" README.md
        sed -i "s|github-readme-stats\.vercel\.app/api/top-langs/?username=\([^&\"]*\)\([^\"]*\)\"|github-readme-stats.vercel.app/api/top-langs/?username=\1\2\&t=${TIMESTAMP}\"|g" README.md
        
        echo "✅ README.md updated successfully"
        
        # 显示修改后的内容（调试用）
        echo "📝 Modified URLs in README.md:"
        grep "github-readme-stats" README.md || echo "Still no github-readme-stats URLs found"
    
    - name: Commit and push changes
      run: |
        git config --local user.email "cacheigcrystal@gmail.com"
        git config --local user.name "IGCrystal"
        git add README.md
        
        # 检查是否有变更需要提交
        if git diff --staged --quiet; then
          echo "ℹ️ No changes detected - README is already up to date"
        else
          echo "✨ Changes detected, committing and pushing..."
          git commit -m "🤖 Auto-update GitHub stats - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push
          echo "✅ README updated and pushed successfully!"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clean up untracked files
      if: always()
      run: |
        # 清理任何可能产生的备份文件
        git clean -f
