name: Update README Profile

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（北京时间 08:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/update-readme.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Update README with latest stats
      run: |
        # 获取当前时间戳，强制刷新GitHub统计API缓存
        TIMESTAMP=$(date +%s)
        
        # 备份原始README
        cp README.md README.backup.md
        
        # 使用sed替换GitHub统计链接，添加时间戳参数来刷新缓存
        sed -i "s|github-readme-stats\.vercel\.app/api?username=Larch-C&show_icons=true&theme=vue&bg_color=00000000&title_color=2F4F4F&text_color=4682B4&icon_color=ADD8E6|github-readme-stats.vercel.app/api?username=Larch-C\&show_icons=true\&theme=vue\&bg_color=00000000\&title_color=2F4F4F\&text_color=4682B4\&icon_color=ADD8E6\&t=${TIMESTAMP}|g" README.md
        
        sed -i "s|github-readme-stats\.vercel\.app/api/top-langs/?username=Larch-C&layout=compact&theme=vue&bg_color=00000000&title_color=2F4F4F&text_color=4682B4|github-readme-stats.vercel.app/api/top-langs/?username=Larch-C\&layout=compact\&theme=vue\&bg_color=00000000\&title_color=2F4F4F\&text_color=4682B4\&t=${TIMESTAMP}|g" README.md
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "cacheigcrystal@gmail.com"
        git config --local user.name "IGCrystal-G"
        git add README.md
        git commit -m "🤖 Auto-update GitHub stats - $(date +'%Y-%m-%d %H:%M:%S UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clean up
      if: always()
      run: |
        if [ -f README.backup.md ]; then
          rm README.backup.md
        fi

  # 可选：添加一个job来验证README格式
  validate-readme:
    runs-on: ubuntu-latest
    needs: update-readme
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Validate README format
      run: |
        echo "📝 Validating README.md format..."
        
        # 检查必要的sections是否存在
        if ! grep -q "ViaLonga Somniviva" README.md; then
          echo "❌ Missing header title"
          exit 1
        fi
        
        if ! grep -q "Herald the dawn of a new world" README.md; then
          echo "❌ Missing subtitle"
          exit 1
        fi
        
        if ! grep -q "github-readme-stats" README.md; then
          echo "❌ Missing GitHub stats"
          exit 1
        fi
        
        if ! grep -q "Created by ❄️IGCrystal" README.md; then
          echo "❌ Missing footer"
          exit 1
        fi
        
        echo "✅ README.md format validation passed!"
    
    - name: Report status
      if: always()
      run: |
        echo "📊 README update completed successfully!"
        echo "🕐 Last updated: $(date +'%Y-%m-%d %H:%M:%S UTC')"
